### ISSUE TITLE
Add pipeviz integration

### ISSUE THREAD

**Issue by sdboyer** [tag1consulting/drupal-deploy-scripts#2]
Meta-issue for adding pipeviz integration to these scripts.

At the highest level, the pattern will be that a `PIPEVIZ_TARGET` environment variable is searched for (presumed to contain the address of a pipeviz server's ingestion port); the presence of this variable is taken as an indication that it is desired that message producers should fire off messages at the target(s) given therein.

For many of the scripts in here, possibly most, it will be sufficient to simply instrument drush. But some will need to be instrumented directly. Because constructing JSON in shell scripts is rather awkward, we'll need a tool to facilitate this, which will probably end up being `pvc`.

**Comment by jeffsheltren** [comment]
Closing wontfix, we can loop back later if needed.
